FROM python:2.7-alpine

LABEL maintainer="autolab-dev@andrew.cmu.edu"

# RUN apk add --no-cache --update build-base \
RUN pip install virtualenv

ENV APP_PATH /home/app/tango
WORKDIR $APP_PATH

RUN mkdir -p volumes

# Add dependencies in separate layer
ADD requirements.txt $APP_PATH

RUN virtualenv .
RUN source $APP_PATH/bin/activate
RUN pip install -r requirements.txt

ADD config.template.py $APP_PATH/config.py

EXPOSE 3000
