FROM python:2.7-alpine

LABEL maintainer="autolab-dev@andrew.cmu.edu"

RUN apk add --no-cache --update docker
RUN pip install virtualenv

ENV APP_PATH /home/app/tango
WORKDIR $APP_PATH

RUN mkdir -p volumes
RUN mkdir -p courselabs

# Add dependencies in separate layer
ADD requirements.txt $APP_PATH

RUN virtualenv .
RUN source bin/activate
RUN pip install -r requirements.txt

ADD config.docker-dev.py config.py

ADD . .

EXPOSE 3000
CMD ["start/start-docker-dev.sh"]
