# Autolab - autograding docker image

FROM ubuntu:14.04
MAINTAINER Mihir Pandya <mihir.m.pandya@gmail.com>

RUN apt-get update && apt-get install -y build-essential wget python

# Install autodriver
WORKDIR /home
RUN useradd autolab && useradd autograde
RUN mkdir autolab autograde output && chown autolab:autolab autolab output && chown autograde:autograde autograde
ADD . /home/autodriver
WORKDIR /home/autodriver
RUN make clean && make && install -c -o root -g root -m 4755 autodriver /usr/bin/autodriver && install -c -m 755 autograde_wrapper.py /usr/bin/autograde_wrapper

ENTRYPOINT ["/usr/bin/autograde_wrapper"]

# Clean up
WORKDIR /home
RUN apt-get remove -y wget && apt-get -y autoremove
RUN rm -rf autodriver

# Check installation
RUN ls -l /home && which autodriver
