FROM ubuntu:bionic
MAINTAINER Zijian an <zijianan@buffalo.edu>

#C++ Setup
RUN apt-get update
RUN apt-get install -y gcc
RUN apt-get install -y make
RUN apt-get install -y build-essential
RUN apt-get install -y libcunit1-dev libcunit1-doc libcunit1


# setup timezone
RUN echo 'Etc/UTC' > /etc/timezone && \
    ln -s /usr/share/zoneinfo/Etc/UTC /etc/localtime && \
    apt-get update && \
    apt-get install -q -y --no-install-recommends tzdata && \
    rm -rf /var/lib/apt/lists/*

# install packages
RUN apt-get update && apt-get install -q -y --no-install-recommends \
    dirmngr \
    gnupg2 \
    build-essential \
    && rm -rf /var/lib/apt/lists/*
# setup keys
RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654

# setup sources.list
RUN echo "deb http://packages.ros.org/ros/ubuntu bionic main" > /etc/apt/sources.list.d/ros1-latest.list

# setup environment
ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8

ENV ROS_DISTRO melodic

# install ros packages
RUN apt-get update && apt-get install -y --no-install-recommends \
    #ros-melodic-ros-core=1.4.1-0* \
    ros-melodic-desktop-full  \
    && rm -rf /var/lib/apt/lists/*

# setup entrypoint
#COPY ./ros_entrypoint.sh /
RUN apt-get update
RUN apt-get install -y git
RUN git clone https://github.com/zijianan/ros_dockerfile.git
RUN chmod +x /ros_dockerfile/ros_entrypoint.sh
ENTRYPOINT ["/ros_dockerfile/ros_entrypoint.sh"]

CMD ["bash"]

#initial work_dic
ENV CATKIN_WS=/root/catkin_ws
RUN mkdir -p $CATKIN_WS/src
#Java Setup
RUN apt-get update --fix-missing
RUN apt-get install -y default-jdk

#Valgrind Setup
RUN apt-get update
RUN apt-get install -y valgrind

#SML Setup
RUN mkdir -p /usr/local/bin/sml
WORKDIR /usr/local/bin/sml
RUN apt-get install -y gcc-multilib g++-multilib lib32z1 lib32ncurses5 wget
RUN wget http://www.smlnj.org/dist/working/110.78/config.tgz
RUN tar -xzvf config.tgz
RUN config/install.sh
RUN ln -s /usr/local/bin/sml/bin/sml /usr/local/sbin/sml
RUN ln -s /usr/local/bin/sml/bin/ml-lex /usr/local/sbin/ml-lex
RUN ln -s /usr/local/bin/sml/bin/ml-yacc /usr/local/sbin/ml-yacc

#Flex setup
RUN apt-get install -y flex

#Bison Setup
RUN apt-get install -y bison

#Utility setup
RUN apt-get install -y unzip

#NodeJS setup
RUN apt-get update --fix-missing
RUN apt-get install -y nodejs
RUN apt-get install -y --no-install-recommends nodejs-dev node-gyp libssl1.0-dev
RUN apt-get install -y npm

#OCaml Setup
RUN apt-get install -y ocaml

# Install autodriver
WORKDIR /home
RUN useradd autolab
RUN useradd autograde
RUN mkdir autolab autograde output
RUN chown autolab:autolab autolab
RUN chown autolab:autolab output
RUN chown autograde:autograde autograde
RUN apt-get update && apt-get install -y sudo 
RUN apt-get install -y git
RUN git clone https://github.com/autolab/Tango.git
WORKDIR Tango/autodriver
RUN make clean && make
RUN cp autodriver /usr/bin/autodriver
RUN chmod +s /usr/bin/autodriver

# Clean up
WORKDIR /home
RUN apt-get -y autoremove
RUN rm -rf Tango/

# Check installation
RUN ls -l /home
RUN which autodriver
RUN which javac
RUN which sml
RUN g++ --version
RUN which ros
