# Autolab - autograding docker image

FROM ubuntu:20.04
MAINTAINER Josh Caskie <jmcaskie@buffalo.edu>

#Utilities and Updates
RUN apt-get update --fix-missing

RUN apt-get install -y apt-utils
RUN apt-get install -y gcc 
RUN apt-get install -y g++ 
RUN apt-get install -y make 
RUN apt-get install -y cmake 
RUN apt-get install -y wget 
RUN apt-get install -y curl 
RUN apt-get install -y build-essential 
RUN apt-get install -y unzip
RUN apt-get install -y gawk 
RUN apt-get install -y git 


#Golang Setup (v1.19.5)
RUN wget https://go.dev/dl/go1.19.5.linux-amd64.tar.gz
RUN rm -rf /usr/local/go && tar -C /usr/local -xzf go1.19.5.linux-amd64.tar.gz
# Update the PATH manually within the image setup
ENV PATH="$PATH:/usr/local/go/bin"

#C++ Setup
# RUN apt-get update
# RUN apt-get install -y gcc
# RUN apt-get install -y make
# RUN apt-get install -y build-essential
# RUN apt-get install -y libcunit1-dev libcunit1-doc libcunit1 curl

#Python Setup
# RUN apt-get update --fix-missing && \
#     DEBIAN_FRONTEND=nointeractive apt-get install -y python2 python-nose pep8 && \
#     curl https://bootstrap.pypa.io/get-pip.py --output get-pip.py && \
#     python2 get-pip.py && pip install --upgrade setuptools numpy pandas sphinx && \
#     ln -s /usr/bin/python2 /usr/bin/python && DEBIAN_FRONTEND=nointeractive \
#     apt-get install -y python3 python3-numpy \
#     python3-nose python3-pandas python3-pip

#Java Setup
# RUN apt-get update --fix-missing
# RUN apt-get install -y default-jdk

#Valgrind Setup
# RUN apt-get update
# RUN apt-get install -y valgrind

#SML Setup
# RUN mkdir -p /usr/local/bin/sml
# WORKDIR /usr/local/bin/sml
# RUN apt-get install -y gcc-multilib g++-multilib lib32z1 lib32ncurses5-dev wget
# RUN wget http://www.smlnj.org/dist/working/110.78/config.tgz
# RUN tar -xzvf config.tgz
# RUN config/install.sh
# RUN ln -s /usr/local/bin/sml/bin/sml /usr/local/sbin/sml
# RUN ln -s /usr/local/bin/sml/bin/ml-lex /usr/local/sbin/ml-lex
# RUN ln -s /usr/local/bin/sml/bin/ml-yacc /usr/local/sbin/ml-yacc

#Flex setup
# RUN apt-get install -y flex

#Bison Setup
# RUN apt-get install -y bison

#NodeJS setup
# RUN apt-get update --fix-missing
# RUN apt-get install -y nodejs
# RUN apt-get install -y npm

#OCaml Setup
# RUN apt-get install -y ocaml


# Install autodriver
WORKDIR /home
RUN useradd autolab
RUN useradd autograde
RUN mkdir autolab autograde output
RUN chown autolab:autolab autolab
RUN chown autolab:autolab output
RUN chown autograde:autograde autograde
RUN apt-get update && apt-get install -y sudo 
RUN apt-get install -y git
RUN git clone https://github.com/UBAutograding/Tango.git
WORKDIR Tango/autodriver
RUN make clean && make
RUN cp autodriver /usr/bin/autodriver
RUN chmod +s /usr/bin/autodriver

# Clean up
WORKDIR /home
RUN apt-get -y autoremove
RUN rm -rf Tango/

# Check installation
RUN ls -l /home
RUN which autodriver
# RUN which javac
# RUN which sml
# RUN g++ --version
RUN go version


# Used for testing Go version upon "docker run <image>"
# CMD go version